[package]
name = "efi"
version = "0.1.0"
authors = ["Bobby Reynolds <bobby@reynoldsbd.net>"]

[dependencies]
bitflags = "1.0"
compiler_builtins = { git = "https://github.com/rust-lang-nursery/compiler-builtins" }
rlibc = "1.0"
spin = "0.4"
