[package]
name = "efi"
version = "0.1.0"
authors = ["Bobby Reynolds <bobby@reynoldsbd.net>"]

[dependencies]
bitflags = "1.0"
rlibc = "1.0"
spin = "0.4"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
